### PR TITLE
LPS-168496

### PR DESCRIPTION
**Pull request by danielCamara02**
https://issues.liferay.com/browse/LPS-168496

### CODE REVIEW

**Comment by danielCamara02** [comment]
ci:test:sf

**Comment by danielCamara02** [comment]
ci:test:search:nocompile

**Comment by danielCamara02** [comment]
ci:stop

**Comment by danielCamara02** [comment]
ci:test:sf

**Comment by danielCamara02** [comment]
ci:test:search:nocompile

**Comment by danielCamara02** [comment]
ci:test:sf

**Comment by danielCamara02** [comment]
ci:test:search:nocompile

**Comment by brookedalton** [comment]
Continued in https://github.com/brookedalton/liferay-portal/pull/148

**Pull request closed without merging**
