### PR TITLE
LPS-170105

### PR DESCRIPTION
**Pull request by CaiocSiqueira**
https://issues.liferay.com/browse/LPS-170105

### CODE REVIEW

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:search:nocompile

**Comment by brookedalton** [comment]
Continued in https://github.com/brookedalton/liferay-portal/pull/164

**Pull request closed without merging**
