### PR TITLE
LPS-174892

### PR DESCRIPTION
**Pull request by danielCamara02**
https://issues.liferay.com/browse/LPS-174892

### CODE REVIEW

**Comment by danielCamara02** [comment]
ci:test:sf

**Comment by danielCamara02** [comment]
ci:test:publications

**Comment by suilin** [comment]
Hi @danielCamara02, thanks for working on it, and I made some small changes to the test
1. We'd better not to use SF to make another changes, you should update it through your first commit.
2. Add several widget in content page we should use targetFragmentName paremeter to target it's position
3. Navigate to content page shpuld use ContentPagesNavigator.openViewContentPage.

**Comment by suilin** [comment]
Pushed to BChan: https://github.com/brianchandotcom/liferay-portal/pull/129978

**Pull request closed without merging**
