### PR TITLE
LPS-167308

### PR DESCRIPTION
**Pull request by CaiocSiqueira**
https://issues.liferay.com/browse/LPS-167308

### CODE REVIEW

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:search:nocompile

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:search:nocompile

**Comment by CaiocSiqueira** [comment]
ci:test:sf
ci:test:search:nocompile

**Comment by CaiocSiqueira** [comment]
ci:test:search:nocompile

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:search:nocompile

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:search

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:search

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:search:nocompile

**Comment by CaiocSiqueira** [comment]
ci:stop

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:search:nocompile

**Comment by CaiocSiqueira** [comment]
ci:test:stop

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:search:nocompile

**Comment by CaiocSiqueira** [comment]
ci:test:search:nocompile

**Comment by brookedalton** [comment]
Continued in https://github.com/brookedalton/liferay-portal/pull/144

**Comment by brookedalton** [comment]
Test looks good! Mostly removing this property https://github.com/brookedalton/liferay-portal/pull/141/files#diff-9501b19017922a33ec98d5a67f6ad086d864e4f8ac75da53d67fa374b8f7bdc7R563 :)

**Pull request closed without merging**
