### PR TITLE
LPS-173850

### PR DESCRIPTION
**Pull request by CaiocSiqueira**
https://issues.liferay.com/browse/LPS-173850

### CODE REVIEW

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:publications:nocompile

**Comment by CaiocSiqueira** [comment]
Original pull request: https://github.com/CaiocSiqueira/liferay-portal/pull/14

**Comment by brookedalton** [comment]
ci:forward

**Comment by brookedalton** [comment]
ci:stop

**Comment by brookedalton** [comment]
ci:forward

**Pull request closed without merging**
