### PR TITLE
LPS-133718test2

### PR DESCRIPTION
**Pull request by brookedalton**

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:search-experiences:norebase

**Comment by brookedalton** [comment]
ci:test:search-experiences:norebase

**Comment by brookedalton** [comment]
ci:test:search-experiences:norebase

**Comment by brookedalton** [comment]
ci:test:search-experiences:norebase

**Comment by brookedalton** [comment]
ci:test:search-experiences:norebase

**Comment by brookedalton** [comment]
ci:test:search-experiences:norebase

**Comment by brookedalton** [comment]
ci:test:search-experiences:norebase

**Comment by brookedalton** [comment]
ci:test:search-experiences:norebase

**Comment by brookedalton** [comment]
ci:test:search-experiences:norebase

**Comment by brookedalton** [comment]
ci:test:search-experiences:norebase

**Comment by brookedalton** [comment]
ci:test:search-experiences:norebase

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by Tim-Cao** [comment]
See https://github.com/brookedalton/liferay-portal/pull/85

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences

**Comment by brookedalton** [comment]
ci:test:search-experiences:norebase

**Pull request closed without merging**
