### PR TITLE
LPS-173127

### PR DESCRIPTION
**Pull request by CaiocSiqueira**
https://issues.liferay.com/browse/LPS-173127

### CODE REVIEW

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:publications:nocompile

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:publications:nocompile

**Comment by brookedalton** [comment]
Continued in https://github.com/brookedalton/liferay-portal/pull/204

**Pull request closed without merging**
