### PR TITLE
LPS-171149

### PR DESCRIPTION
**Pull request by CaiocSiqueira**
https://issues.liferay.com/browse/LPS-171149

### CODE REVIEW

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:publications

**Comment by CaiocSiqueira** [comment]
ci:test:publications

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:forward

**Pull request closed without merging**
