### PR TITLE
LPS-173200

### PR DESCRIPTION
**Pull request by danielCamara02**
https://issues.liferay.com/browse/LPS-173200

### CODE REVIEW

**Comment by danielCamara02** [comment]
ci:test:sf

**Comment by danielCamara02** [comment]
ci:test:search:nocompile

**Comment by danielCamara02** [comment]
ci:test:search:nocompile

**Comment by xbrianlee** [comment]
Continued in https://github.com/xbrianlee/liferay-portal/pull/1105

**Pull request closed without merging**
