### PR TITLE
LPS-169880

### PR DESCRIPTION
**Pull request by danielCamara02**
https://issues.liferay.com/browse/LPS-169880

### CODE REVIEW

**Comment by danielCamara02** [comment]
ci:test:sf

**Comment by danielCamara02** [comment]
ci:test:search:nocompile

**Comment by danielCamara02** [comment]
ci:test:sf

**Comment by danielCamara02** [comment]
ci:test:sf

**Comment by danielCamara02** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:forward

**Pull request closed without merging**
